spring:
  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  cache:
    jcache:
      config: classpath:ehcache.xml
  artemis:
    user: artemis
    password: artemis

brewery.inventory.address: http://localhost:8082
